### ISSUE TITLE
cusCastSetFormat symbol is missing in clarius-cast-v801-linux libraries

### ISSUE THREAD

**Issue by daudrain** [clariusdev/cast#31]
Hi Clarius,

While adding more options to caster example available on master branch, `cusCastSetFormat` appears to be missing from `clarius-cast-v801-linux.zip` libraries:
```
~/sources/github.com/clariusdev/cast/src/example/caster$ make
mkdir -p build/./
g++ -I./ -I./build -I../../include -std=gnu++14 -c main.cpp -o build/./main.cpp.o
g++ ./build/./main.cpp.o -o build/caster -L../../lib -lcast -lpthread
/usr/bin/ld: ./build/./main.cpp.o: in function `init(int&, char**)':
main.cpp:(.text+0x15d5): undefined reference to `cusCastSetFormat'
collect2: error: ld returned 1 exit status
make: *** [Makefile:24: build/caster] Error 1
```

This can be reproduced with this fork: https://github.com/daudrain/cast.

**Comment by clariusk** [comment]
should be fixed now in 8.6.0 release.

**Comment by daudrain** [comment]
`cusCastSetFormat` is still missing in clarius-cast-v860-linux

```
>nm -gD libcast.so | grep cusCast
0000000000416806 T cusCastConnect
00000000004162bd T cusCastDestroy
000000000041693d T cusCastDisconnect
0000000000416433 T cusCastInit
0000000000414c06 T cusCastIsConnected
0000000000416db0 T cusCastReadRawData
0000000000416cc0 T cusCastRequestRawData
0000000000416b01 T cusCastSeparateOverlays
0000000000414cfd T cusCastSetButtonFn
0000000000414d4f T cusCastSetErrorFn
0000000000414cd4 T cusCastSetFreezeFn
0000000000416a1b T cusCastSetOutputSize
0000000000414c82 T cusCastSetProcessedImageFn
0000000000414d26 T cusCastSetProgressFn
0000000000414c59 T cusCastSetRawImageFn
0000000000414cab T cusCastSetSpectralImageFn
0000000000416e96 T cusCastUserFunction
```

**Comment by clariusk** [comment]
thanks for catching, this was caught recently, and our 8.7.0 release has fixed this, will update when any beta's are available.

**Comment by clariusk** [comment]
should be fixed now with latest release, thanks for patience!
